### ISSUE TITLE
Error with espree.js

### ISSUE THREAD

**Issue by brandonbuttars** [PolymerLabs/polybuild#4]
Getting a building error and it seems to involve espree.js

```
Error: Line 8: Unexpected token }
    at throwError (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2069:17)
    at throwUnexpected (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2132:5)
    at parsePrimaryExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2887:8)
    at parseLeftHandSideExpressionAllowCall (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:2974:57)
    at parsePostfixExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3023:12)
    at parseUnaryExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3083:16)
    at parseBinaryExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3175:12)
    at parseConditionalExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3236:12)
    at parseAssignmentExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3473:19)
    at parseExpression (/Users/UserName/Project/node_modules/polybuild/node_modules/gulp-vulcanize/node_modules/vulcanize/node_modules/hydrolysis/node_modules/espree/espree.js:3523:16)
```

**Comment by justinfagnani** [comment]
This would be an issue in Hydrolysis, if not Espree. Closing for now, as it's old. Reopen on Hydrolysis if it's still an issue.
